//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.Diagnostics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CpuFeatures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CpuFeatures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.Diagnostics.Resources.CpuFeatures", typeof(CpuFeatures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1GB pages supported.
        /// </summary>
        internal static string _1GB_PAGE {
            get {
                return ResourceManager.GetString("1GB_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Monitoring and Software Controlled Clock Facilities.
        /// </summary>
        internal static string ACPI {
            get {
                return ResourceManager.GetString("ACPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADCX (unsigned integer addition with carry flag) instruction.
        /// </summary>
        internal static string ADX {
            get {
                return ResourceManager.GetString("ADX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES 128bit instruction Extensions.
        /// </summary>
        internal static string AESNI {
            get {
                return ResourceManager.GetString("AESNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-chip APIC hardware.
        /// </summary>
        internal static string APIC {
            get {
                return ResourceManager.GetString("APIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Vector Extensions.
        /// </summary>
        internal static string AVX {
            get {
                return ResourceManager.GetString("AVX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Vector Extensions 2.
        /// </summary>
        internal static string AVX2 {
            get {
                return ResourceManager.GetString("AVX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 packed single precision fused multiply add instructions. Intel(R) Xeon Phi(TM) only.
        /// </summary>
        internal static string AVX512_4FMAPS {
            get {
                return ResourceManager.GetString("AVX512_4FMAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 dotproduct multiplication instructions. Intel(R) Xeon Phi(TM) only.
        /// </summary>
        internal static string AVX512_4VNNIW {
            get {
                return ResourceManager.GetString("AVX512_4VNNIW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 bit counting instructions.
        /// </summary>
        internal static string AVX512_BITALG {
            get {
                return ResourceManager.GetString("AVX512_BITALG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 Fuse Multiply Add instructions.
        /// </summary>
        internal static string AVX512_IFMA {
            get {
                return ResourceManager.GetString("AVX512_IFMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 bit manipulation instructions (VPERMB, VPERMI2B, VPERMT2B, VPMULTISHIFTQB).
        /// </summary>
        internal static string AVX512_VBMI {
            get {
                return ResourceManager.GetString("AVX512_VBMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 bit manipulation instructions (VPCOMPRESSB, VCOMPRESSW, VPEXPANDB, VPEXPANDW, VPSHLD, VPSHLDV, VPSHRD, VPSHRDV).
        /// </summary>
        internal static string AVX512_VBMI2 {
            get {
                return ResourceManager.GetString("AVX512_VBMI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 multiply and add instructions (VPDPBUSD, VPDPBUSDS, VPDPWSSD, VPDPWSSDS).
        /// </summary>
        internal static string AVX512_VNNI {
            get {
                return ResourceManager.GetString("AVX512_VNNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 instructions VPOPCNTDQ. Intel(R) Xeon Phi(TM) only.
        /// </summary>
        internal static string AVX512_VPOPCNTDQ {
            get {
                return ResourceManager.GetString("AVX512_VPOPCNTDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 32/64-bit vector mask instructions.
        /// </summary>
        internal static string AVX512BW {
            get {
                return ResourceManager.GetString("AVX512BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 change detection, broadcast mask instructions.
        /// </summary>
        internal static string AVX512CD {
            get {
                return ResourceManager.GetString("AVX512CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 16-bit vector mask instructions.
        /// </summary>
        internal static string AVX512DQ {
            get {
                return ResourceManager.GetString("AVX512DQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 approximate exponential instructions. Intel(R) Xeon Phi(TM) only.
        /// </summary>
        internal static string AVX512ER {
            get {
                return ResourceManager.GetString("AVX512ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 8-bit vector mask instructions.
        /// </summary>
        internal static string AVX512F {
            get {
                return ResourceManager.GetString("AVX512F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 prefetch instructions. Intel(R) Xeon Phi(TM) only.
        /// </summary>
        internal static string AVX512PF {
            get {
                return ResourceManager.GetString("AVX512PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 vector x/y instructions.
        /// </summary>
        internal static string AVX512VL {
            get {
                return ResourceManager.GetString("AVX512VL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit manipulation instructions (ANDN, BEXTR, BLSI, BLSR, TZCNT).
        /// </summary>
        internal static string BMI1 {
            get {
                return ResourceManager.GetString("BMI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit manipulation instructions (BZHI, MULX, PDEP, PEXT, RORX, SARX/SHLX/SHRX.
        /// </summary>
        internal static string BMI2 {
            get {
                return ResourceManager.GetString("BMI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CET indirect branch tracking.
        /// </summary>
        internal static string CET_IBT {
            get {
                return ResourceManager.GetString("CET_IBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports CET shadow stack features.
        /// </summary>
        internal static string CET_SS {
            get {
                return ResourceManager.GetString("CET_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache line demote.
        /// </summary>
        internal static string CLDEMOTE {
            get {
                return ResourceManager.GetString("CLDEMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLFLUSHOPT (flush cache line optimized) instruction.
        /// </summary>
        internal static string CLFLUSHOPT {
            get {
                return ResourceManager.GetString("CLFLUSHOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLFLUSH (flush cache line) instruction.
        /// </summary>
        internal static string CLFSH {
            get {
                return ResourceManager.GetString("CLFSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLWB (Cache line write back) instruction.
        /// </summary>
        internal static string CLWB {
            get {
                return ResourceManager.GetString("CLWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Move Instruction.
        /// </summary>
        internal static string CMOV {
            get {
                return ResourceManager.GetString("CMOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMPXCHG16B (compare/exchange atomically 128-bit) instruction.
        /// </summary>
        internal static string CMPXCHG16B {
            get {
                return ResourceManager.GetString("CMPXCHG16B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L1 Context ID.
        /// </summary>
        internal static string CNXT_ID {
            get {
                return ResourceManager.GetString("CNXT-ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMPXCHG8 instruction.
        /// </summary>
        internal static string CX8 {
            get {
                return ResourceManager.GetString("CX8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Cache Access.
        /// </summary>
        internal static string DCA {
            get {
                return ResourceManager.GetString("DCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Extension.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Store.
        /// </summary>
        internal static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPL Qualified Debug Store.
        /// </summary>
        internal static string DS_CPL {
            get {
                return ResourceManager.GetString("DS-CPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-Bit Debug Store. The processor has the ability to write a history of the 64-bit branch to and from addresses into a memory buffer.
        /// </summary>
        internal static string DTES64 {
            get {
                return ResourceManager.GetString("DTES64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Intel SpeedStep(R) Technology.
        /// </summary>
        internal static string EIST {
            get {
                return ResourceManager.GetString("EIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit floating-point conversion instructions.
        /// </summary>
        internal static string F16C {
            get {
                return ResourceManager.GetString("F16C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast REP MOV.
        /// </summary>
        internal static string FAST_REP_MOV {
            get {
                return ResourceManager.GetString("FAST REP MOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x87 FPU Data Pointer updated only on x87 exceptions.
        /// </summary>
        internal static string FDP_EXCPTN_ONLY {
            get {
                return ResourceManager.GetString("FDP_EXCPTN_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fused Multiply Add.
        /// </summary>
        internal static string FMA {
            get {
                return ResourceManager.GetString("FMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating-point Unit On-Chip.
        /// </summary>
        internal static string FPU {
            get {
                return ResourceManager.GetString("FPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprecates FPU CS and FPU DS values.
        /// </summary>
        internal static string FPU_CS_DEP {
            get {
                return ResourceManager.GetString("FPU-CS DEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDFSBASE/RDGSBSAE/WRFSBASE/WRGSBASE instructions.
        /// </summary>
        internal static string FSGSBASE {
            get {
                return ResourceManager.GetString("FSGSBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FXSAVE and FXSTOR instructions.
        /// </summary>
        internal static string FXSR {
            get {
                return ResourceManager.GetString("FXSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX Galois Field instructions.
        /// </summary>
        internal static string GFNI {
            get {
                return ResourceManager.GetString("GFNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware lock elision instructions.
        /// </summary>
        internal static string HLE {
            get {
                return ResourceManager.GetString("HLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Threading.
        /// </summary>
        internal static string HTT {
            get {
                return ResourceManager.GetString("HTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor identified as a hybrid part.
        /// </summary>
        internal static string HYBRID {
            get {
                return ResourceManager.GetString("HYBRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_ARCH_CAPABILITIES MSR supported, CPU specific.
        /// </summary>
        internal static string IA32_ARCH_CAPABILITIES {
            get {
                return ResourceManager.GetString("IA32_ARCH_CAPABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_CORE_CAPABILITIES MSR supported, CPU specific.
        /// </summary>
        internal static string IA32_CORE_CAPABILITIES {
            get {
                return ResourceManager.GetString("IA32_CORE_CAPABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_TSC_ADJUST MSR.
        /// </summary>
        internal static string IA32_TSC_ADJUST {
            get {
                return ResourceManager.GetString("IA32_TSC_ADJUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) 64 Instruction Set Architecture.
        /// </summary>
        internal static string IA64 {
            get {
                return ResourceManager.GetString("IA64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect branch restricted speculation (IBRS) and indirect branch predictor barrier (IBPB).
        /// </summary>
        internal static string IBRS_IBPB {
            get {
                return ResourceManager.GetString("IBRS/IBPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVPCID instruction for system software that manages process-context identifiers.
        /// </summary>
        internal static string INVPCID {
            get {
                return ResourceManager.GetString("INVPCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_FLUSH_CMD MSR supported.
        /// </summary>
        internal static string L1D_FLUSH {
            get {
                return ResourceManager.GetString("L1D_FLUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAHF and SAHF instructions available when IA-32e mode is enabled and in 64-bit submode.
        /// </summary>
        internal static string LAHF {
            get {
                return ResourceManager.GetString("LAHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZCNT (count leading zero bits) instruction.
        /// </summary>
        internal static string LZCNT {
            get {
                return ResourceManager.GetString("LZCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine-Check Architecture.
        /// </summary>
        internal static string MCA {
            get {
                return ResourceManager.GetString("MCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine-Check Exception.
        /// </summary>
        internal static string MCE {
            get {
                return ResourceManager.GetString("MCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD_CLEAR supported.
        /// </summary>
        internal static string MD_CLEAR {
            get {
                return ResourceManager.GetString("MD_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMX Technologies.
        /// </summary>
        internal static string MMX {
            get {
                return ResourceManager.GetString("MMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONITOR and MWAIT instructions.
        /// </summary>
        internal static string MONITOR {
            get {
                return ResourceManager.GetString("MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVBE instruction.
        /// </summary>
        internal static string MOVBE {
            get {
                return ResourceManager.GetString("MOVBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVDIR64B instruction.
        /// </summary>
        internal static string MOVDIR64B {
            get {
                return ResourceManager.GetString("MOVDIR64B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVDIRI instruction.
        /// </summary>
        internal static string MOVDIRI {
            get {
                return ResourceManager.GetString("MOVDIRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Memory Protection Extensions.
        /// </summary>
        internal static string MPX {
            get {
                return ResourceManager.GetString("MPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Specific Registers.
        /// </summary>
        internal static string MSR {
            get {
                return ResourceManager.GetString("MSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Type Range Registers.
        /// </summary>
        internal static string MTRR {
            get {
                return ResourceManager.GetString("MTRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS has set CR4.PKE to enable protection keys (and the RDPKRU/WRPKRU instructions).
        /// </summary>
        internal static string OSPKE {
            get {
                return ResourceManager.GetString("OSPKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS-Enabled Extended State Management.
        /// </summary>
        internal static string OSXSAVE {
            get {
                return ResourceManager.GetString("OSXSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Address Extension.
        /// </summary>
        internal static string PAE {
            get {
                return ResourceManager.GetString("PAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Attribute Table.
        /// </summary>
        internal static string PAT {
            get {
                return ResourceManager.GetString("PAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Break Enable.
        /// </summary>
        internal static string PBE {
            get {
                return ResourceManager.GetString("PBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Context Identifiers.
        /// </summary>
        internal static string PCID {
            get {
                return ResourceManager.GetString("PCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCLMULQDQ Instruction.
        /// </summary>
        internal static string PCLMULQDQ {
            get {
                return ResourceManager.GetString("PCLMULQDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfmon and Debug Capability.
        /// </summary>
        internal static string PDCM {
            get {
                return ResourceManager.GetString("PDCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Global Enable.
        /// </summary>
        internal static string PGE {
            get {
                return ResourceManager.GetString("PGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection keys for supervisor-mode pages.
        /// </summary>
        internal static string PKS {
            get {
                return ResourceManager.GetString("PKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Keys for User Mode.
        /// </summary>
        internal static string PKU {
            get {
                return ResourceManager.GetString("PKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPCNT instruction.
        /// </summary>
        internal static string POPCNT {
            get {
                return ResourceManager.GetString("POPCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefetch data into caches in anticipation of a write.
        /// </summary>
        internal static string PREFETCHW {
            get {
                return ResourceManager.GetString("PREFETCHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefetch data into caches in anticipation of a write, with T1 hint. Intel(R) Xeon Phi(TM) only.
        /// </summary>
        internal static string PREFETCHWT1 {
            get {
                return ResourceManager.GetString("PREFETCHWT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel Processor Trace.
        /// </summary>
        internal static string PROCTRC {
            get {
                return ResourceManager.GetString("PROCTRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size Extension.
        /// </summary>
        internal static string PSE {
            get {
                return ResourceManager.GetString("PSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36-bit Page Size Extension.
        /// </summary>
        internal static string PSE_36 {
            get {
                return ResourceManager.GetString("PSE-36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Serial Number is present and enabled.
        /// </summary>
        internal static string PSN {
            get {
                return ResourceManager.GetString("PSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPID and IA32_TSX_AUX.
        /// </summary>
        internal static string RDPID {
            get {
                return ResourceManager.GetString("RDPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDRAND (read random number) instruction.
        /// </summary>
        internal static string RDRAND {
            get {
                return ResourceManager.GetString("RDRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDSEED (read random seed) instruction.
        /// </summary>
        internal static string RDSEED {
            get {
                return ResourceManager.GetString("RDSEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Resource Director Technology Allocation.
        /// </summary>
        internal static string RDT_A {
            get {
                return ResourceManager.GetString("RDT-A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Resource Director Technology Monitoring.
        /// </summary>
        internal static string RDT_M {
            get {
                return ResourceManager.GetString("RDT-M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDTSCP and IA32_TSX_AUX supported.
        /// </summary>
        internal static string RDTSCP {
            get {
                return ResourceManager.GetString("RDTSCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced REP MOVSB/STOSB.
        /// </summary>
        internal static string REP_MOVSB_STOSB {
            get {
                return ResourceManager.GetString("REP MOVSB/STOSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTM transaction.
        /// </summary>
        internal static string RTM {
            get {
                return ResourceManager.GetString("RTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silicon Debug (IA32_DEBUG_INTERFACE MSR).
        /// </summary>
        internal static string SDBG {
            get {
                return ResourceManager.GetString("SDBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast System Call.
        /// </summary>
        internal static string SEP {
            get {
                return ResourceManager.GetString("SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Software Guard Extensions.
        /// </summary>
        internal static string SGX {
            get {
                return ResourceManager.GetString("SGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGX Launch Configuration.
        /// </summary>
        internal static string SGX_LC {
            get {
                return ResourceManager.GetString("SGX_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Secure Hash Algorithm Extensions.
        /// </summary>
        internal static string SHA {
            get {
                return ResourceManager.GetString("SHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Mode Access Prevention.
        /// </summary>
        internal static string SMAP {
            get {
                return ResourceManager.GetString("SMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Mode Execution Prevention.
        /// </summary>
        internal static string SMEP {
            get {
                return ResourceManager.GetString("SMEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safer Mode Extensions.
        /// </summary>
        internal static string SMX {
            get {
                return ResourceManager.GetString("SMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Snoop.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speculative Store Bypass Disable (SSBD).
        /// </summary>
        internal static string SSBD {
            get {
                return ResourceManager.GetString("SSBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions.
        /// </summary>
        internal static string SSE {
            get {
                return ResourceManager.GetString("SSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 2.
        /// </summary>
        internal static string SSE2 {
            get {
                return ResourceManager.GetString("SSE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 3.
        /// </summary>
        internal static string SSE3 {
            get {
                return ResourceManager.GetString("SSE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 4.1.
        /// </summary>
        internal static string SSE4_1 {
            get {
                return ResourceManager.GetString("SSE4.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 4.2.
        /// </summary>
        internal static string SSE4_2 {
            get {
                return ResourceManager.GetString("SSE4.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Streaming SIMD Extensions 3.
        /// </summary>
        internal static string SSSE3 {
            get {
                return ResourceManager.GetString("SSSE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single thread indirect branch predictors (STIBP).
        /// </summary>
        internal static string STIBP {
            get {
                return ResourceManager.GetString("STIBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSCALL and SYSRET instructions are supported.
        /// </summary>
        internal static string SYSCALL {
            get {
                return ResourceManager.GetString("SYSCALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Monitor.
        /// </summary>
        internal static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Monitor 2.
        /// </summary>
        internal static string TM2 {
            get {
                return ResourceManager.GetString("TM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp Counter.
        /// </summary>
        internal static string TSC {
            get {
                return ResourceManager.GetString("TSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp Counter Deadline.
        /// </summary>
        internal static string TSC_DEADLINE {
            get {
                return ResourceManager.GetString("TSC-DEADLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-mode Instruction Prevention.
        /// </summary>
        internal static string UMIP {
            get {
                return ResourceManager.GetString("UMIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES 128-bit on vectored data 256bit registers.
        /// </summary>
        internal static string VAES {
            get {
                return ResourceManager.GetString("VAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Mode Extension.
        /// </summary>
        internal static string VME {
            get {
                return ResourceManager.GetString("VME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Maxhine Extensions.
        /// </summary>
        internal static string VMX {
            get {
                return ResourceManager.GetString("VMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPCLMULQDQ Instruction.
        /// </summary>
        internal static string VPCLMULQDQ {
            get {
                return ResourceManager.GetString("VPCLMULQDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait (TPAUSE, UMONITOR, UMWAIT) instructions.
        /// </summary>
        internal static string WAITPKG {
            get {
                return ResourceManager.GetString("WAITPKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended APIC support.
        /// </summary>
        internal static string X2APIC {
            get {
                return ResourceManager.GetString("X2APIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Disable bit.
        /// </summary>
        internal static string XD {
            get {
                return ResourceManager.GetString("XD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSAVE/XSTOR states.
        /// </summary>
        internal static string XSAVE {
            get {
                return ResourceManager.GetString("XSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xTPR Update Control.
        /// </summary>
        internal static string XTPR {
            get {
                return ResourceManager.GetString("XTPR", resourceCulture);
            }
        }
    }
}
