//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.Diagnostics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CpuFeatures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CpuFeatures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.Diagnostics.Resources.CpuFeatures", typeof(CpuFeatures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1GB pages supported.
        /// </summary>
        internal static string _1GB_PAGE {
            get {
                return ResourceManager.GetString("1GB_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DNow!™ instructions.
        /// </summary>
        internal static string _3DNOW {
            get {
                return ResourceManager.GetString("3DNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMD extensions to 3DNow! instructions.
        /// </summary>
        internal static string _3DNOWEXT {
            get {
                return ResourceManager.GetString("3DNOWEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZCNT (count leading zero bits) instruction.
        /// </summary>
        internal static string ABM {
            get {
                return ResourceManager.GetString("ABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Monitoring and Software Controlled Clock Facilities.
        /// </summary>
        internal static string ACPI {
            get {
                return ResourceManager.GetString("ACPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address mask extension support for instruction breakpoint.
        /// </summary>
        internal static string ADMSK {
            get {
                return ResourceManager.GetString("ADMSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Precision Add-Carry Instruction Extensions.
        /// </summary>
        internal static string ADX {
            get {
                return ResourceManager.GetString("ADX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES 128bit instruction Extensions.
        /// </summary>
        internal static string AESNI {
            get {
                return ResourceManager.GetString("AESNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAHF and SAHF instructions available when IA-32e mode is enabled and in 64-bit submode.
        /// </summary>
        internal static string AHF64 {
            get {
                return ResourceManager.GetString("AHF64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCK MOV CR0 means MOV CR8.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile computation on bfloat16 numbers.
        /// </summary>
        internal static string AMX_BF16 {
            get {
                return ResourceManager.GetString("AMX_BF16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile computation on 8-bit integers.
        /// </summary>
        internal static string AMX_INT8 {
            get {
                return ResourceManager.GetString("AMX_INT8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile architecture.
        /// </summary>
        internal static string AMX_TILE {
            get {
                return ResourceManager.GetString("AMX_TILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-chip Advanced Programmable Interrupt Controller hardware.
        /// </summary>
        internal static string APIC {
            get {
                return ResourceManager.GetString("APIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP Error Pointers Restored by XRSTOR.
        /// </summary>
        internal static string ASRFPEP {
            get {
                return ResourceManager.GetString("ASRFPEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Vector Extensions.
        /// </summary>
        internal static string AVX {
            get {
                return ResourceManager.GetString("AVX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX Vector Neural Network Instructions.
        /// </summary>
        internal static string AVX_VNNI {
            get {
                return ResourceManager.GetString("AVX_VNNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Vector Extensions 2.
        /// </summary>
        internal static string AVX2 {
            get {
                return ResourceManager.GetString("AVX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 packed single precision fused multiply add instructions.
        /// </summary>
        internal static string AVX512_4FMAPS {
            get {
                return ResourceManager.GetString("AVX512_4FMAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 4-register neural network instructions.
        /// </summary>
        internal static string AVX512_4VNNIW {
            get {
                return ResourceManager.GetString("AVX512_4VNNIW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 bfloat16 instructions.
        /// </summary>
        internal static string AVX512_BF16 {
            get {
                return ResourceManager.GetString("AVX512_BF16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 bit counting instructions.
        /// </summary>
        internal static string AVX512_BITALG {
            get {
                return ResourceManager.GetString("AVX512_BITALG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 float16 instructions.
        /// </summary>
        internal static string AVX512_FP16 {
            get {
                return ResourceManager.GetString("AVX512_FP16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 Integer Fuse Multiply Add instructions.
        /// </summary>
        internal static string AVX512_IFMA {
            get {
                return ResourceManager.GetString("AVX512_IFMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 bit manipulation instructions (VPERMB, VPERMI2B, VPERMT2B, VPMULTISHIFTQB).
        /// </summary>
        internal static string AVX512_VBMI {
            get {
                return ResourceManager.GetString("AVX512_VBMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 bit manipulation instructions (VPCOMPRESSB, VCOMPRESSW, VPEXPANDB, VPEXPANDW, VPSHLD, VPSHLDV, VPSHRD, VPSHRDV).
        /// </summary>
        internal static string AVX512_VBMI2 {
            get {
                return ResourceManager.GetString("AVX512_VBMI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 neural network instructions (VPDPBUSD, VPDPBUSDS, VPDPWSSD, VPDPWSSDS).
        /// </summary>
        internal static string AVX512_VNNI {
            get {
                return ResourceManager.GetString("AVX512_VNNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 VP2INTERSECT double/quad word instructions.
        /// </summary>
        internal static string AVX512_VP2INTERSECT {
            get {
                return ResourceManager.GetString("AVX512_VP2INTERSECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 population count double/quad word instructions.
        /// </summary>
        internal static string AVX512_VPOPCNTDQ {
            get {
                return ResourceManager.GetString("AVX512_VPOPCNTDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 byte and word instructions.
        /// </summary>
        internal static string AVX512BW {
            get {
                return ResourceManager.GetString("AVX512BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 conflict detection, broadcast mask instructions.
        /// </summary>
        internal static string AVX512CD {
            get {
                return ResourceManager.GetString("AVX512CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 double/quadword instructions.
        /// </summary>
        internal static string AVX512DQ {
            get {
                return ResourceManager.GetString("AVX512DQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 approximate exponential and reciprocal instructions.
        /// </summary>
        internal static string AVX512ER {
            get {
                return ResourceManager.GetString("AVX512ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 foundation instructions.
        /// </summary>
        internal static string AVX512F {
            get {
                return ResourceManager.GetString("AVX512F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 prefetch instructions.
        /// </summary>
        internal static string AVX512PF {
            get {
                return ResourceManager.GetString("AVX512PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX512 vector length instructions.
        /// </summary>
        internal static string AVX512VL {
            get {
                return ResourceManager.GetString("AVX512VL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_SPEC_CTRL MSR allows enable of BHI_DIS_S behaviour.
        /// </summary>
        internal static string BHI_CTRL {
            get {
                return ResourceManager.GetString("BHI_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit manipulation instructions (ANDN, BEXTR, BLSI, BLSR, TZCNT).
        /// </summary>
        internal static string BMI1 {
            get {
                return ResourceManager.GetString("BMI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit manipulation instructions (BZHI, MULX, PDEP, PEXT, RORX, SARX/SHLX/SHRX.
        /// </summary>
        internal static string BMI2 {
            get {
                return ResourceManager.GetString("BMI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for OS bus-lock detection.
        /// </summary>
        internal static string BUS_LOCK_DETECT {
            get {
                return ResourceManager.GetString("BUS_LOCK_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CET indirect branch tracking.
        /// </summary>
        internal static string CET_IBT {
            get {
                return ResourceManager.GetString("CET_IBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control flow enforcement (CET) shadow stack features.
        /// </summary>
        internal static string CET_SS {
            get {
                return ResourceManager.GetString("CET_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control flow enforcement (CET) supervisor shadow stack features.
        /// </summary>
        internal static string CET_SSS {
            get {
                return ResourceManager.GetString("CET_SSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache line demote.
        /// </summary>
        internal static string CLDEMOTE {
            get {
                return ResourceManager.GetString("CLDEMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLFLUSHOPT (flush cache line optimized) instruction, support persistent memory programming.
        /// </summary>
        internal static string CLFLUSHOPT {
            get {
                return ResourceManager.GetString("CLFLUSHOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLFLUSH (flush cache line) instruction.
        /// </summary>
        internal static string CLFSH {
            get {
                return ResourceManager.GetString("CLFSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLWB (Cache line write back) instruction, support persistent memory programming.
        /// </summary>
        internal static string CLWB {
            get {
                return ResourceManager.GetString("CLWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLZERO instruction supported.
        /// </summary>
        internal static string CLZERO {
            get {
                return ResourceManager.GetString("CLZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Move Instruction.
        /// </summary>
        internal static string CMOV {
            get {
                return ResourceManager.GetString("CMOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Multi-processing Legacy Mode.
        /// </summary>
        internal static string CMP {
            get {
                return ResourceManager.GetString("CMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMPXCHG16B (compare/exchange atomically 128-bit) instruction.
        /// </summary>
        internal static string CMPXCHG16B {
            get {
                return ResourceManager.GetString("CMPXCHG16B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L1 Context ID.
        /// </summary>
        internal static string CNXT_ID {
            get {
                return ResourceManager.GetString("CNXT-ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMPXCHG8 instruction.
        /// </summary>
        internal static string CX8 {
            get {
                return ResourceManager.GetString("CX8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data access breakpoint extension.
        /// </summary>
        internal static string DBE {
            get {
                return ResourceManager.GetString("DBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Cache Access for DMA writes.
        /// </summary>
        internal static string DCA {
            get {
                return ResourceManager.GetString("DCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_SPEC_CTRL MSR allows disable of Data Dependent Prefetcher.
        /// </summary>
        internal static string DDPD_U {
            get {
                return ResourceManager.GetString("DDPD_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Extensions.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Store, trace of executed jumps.
        /// </summary>
        internal static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPL Qualified Debug Store.
        /// </summary>
        internal static string DS_CPL {
            get {
                return ResourceManager.GetString("DS-CPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-Bit Debug Store. The processor has the ability to write a history of the 64-bit branch to and from addresses into a memory buffer.
        /// </summary>
        internal static string DTES64 {
            get {
                return ResourceManager.GetString("DTES64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFER.LMSLE (Extended Feature Enable Register, Long Mode Segment Limit Enable) is unsupported.
        /// </summary>
        internal static string EFER_LMSLE {
            get {
                return ResourceManager.GetString("EFER.LMSLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Intel SpeedStep(R) Technology.
        /// </summary>
        internal static string EIST {
            get {
                return ResourceManager.GetString("EIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Stores.
        /// </summary>
        internal static string ENQCMD {
            get {
                return ResourceManager.GetString("ENQCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced REP MOVSB/STOSB.
        /// </summary>
        internal static string ERMS {
            get {
                return ResourceManager.GetString("ERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEV (Secure Encrypted Virtualization) Encrypted State supported.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended APIC space. Presence of extended APIC register.
        /// </summary>
        internal static string EXTAPICSPACE {
            get {
                return ResourceManager.GetString("EXTAPICSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit floating-point conversion (half precision) instructions.
        /// </summary>
        internal static string F16C {
            get {
                return ResourceManager.GetString("F16C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x87 FPU Data Pointer updated only on x87 exceptions.
        /// </summary>
        internal static string FDP_EXCPTN_ONLY {
            get {
                return ResourceManager.GetString("FDP_EXCPTN_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FXSAVE and FXRSTOR instruction optimizations.
        /// </summary>
        internal static string FFXSR {
            get {
                return ResourceManager.GetString("FFXSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fused Multiply Add (FMA3) 3-operand.
        /// </summary>
        internal static string FMA {
            get {
                return ResourceManager.GetString("FMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four-operand FMA instruction support.
        /// </summary>
        internal static string FMA4 {
            get {
                return ResourceManager.GetString("FMA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating-point Unit On-Chip.
        /// </summary>
        internal static string FPU {
            get {
                return ResourceManager.GetString("FPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprecates FPU CS and FPU DS values.
        /// </summary>
        internal static string FPU_CS_DEP {
            get {
                return ResourceManager.GetString("FPU-CS DEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Short CMPSB, SCASB.
        /// </summary>
        internal static string FSCMPSB {
            get {
                return ResourceManager.GetString("FSCMPSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/Write register FS/GS instructions.
        /// </summary>
        internal static string FSGSBASE {
            get {
                return ResourceManager.GetString("FSGSBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast short REP MOV.
        /// </summary>
        internal static string FSRM {
            get {
                return ResourceManager.GetString("FSRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Short STOSB.
        /// </summary>
        internal static string FSSTOSB {
            get {
                return ResourceManager.GetString("FSSTOSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FXSAVE and FXSTOR instructions.
        /// </summary>
        internal static string FXSR {
            get {
                return ResourceManager.GetString("FXSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Zero-Length MOVSB.
        /// </summary>
        internal static string FZMOVSB {
            get {
                return ResourceManager.GetString("FZMOVSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVX Galois Field instructions.
        /// </summary>
        internal static string GFNI {
            get {
                return ResourceManager.GetString("GFNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSX Hardware lock elision instructions.
        /// </summary>
        internal static string HLE {
            get {
                return ResourceManager.GetString("HLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports IA32_HRESET_ENABLE MSR (Processor Reset History).
        /// </summary>
        internal static string HRESET {
            get {
                return ResourceManager.GetString("HRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Threading.
        /// </summary>
        internal static string HTT {
            get {
                return ResourceManager.GetString("HTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor identified as a hybrid part.
        /// </summary>
        internal static string HYBRID {
            get {
                return ResourceManager.GetString("HYBRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU is running in Hypervisor mode.
        /// </summary>
        internal static string HYPERVISOR {
            get {
                return ResourceManager.GetString("HYPERVISOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speculative Side Channel mitigates, IA32_ARCH_CAPABILITIES MSR supported, CPU specific.
        /// </summary>
        internal static string IA32_ARCH_CAPABILITIES {
            get {
                return ResourceManager.GetString("IA32_ARCH_CAPABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for a MSR listing model-specific core capabilities, IA32_CORE_CAPABILITIES MSR supported, CPU specific.
        /// </summary>
        internal static string IA32_CORE_CAPABILITIES {
            get {
                return ResourceManager.GetString("IA32_CORE_CAPABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates the presence of the IA32_PPIN and IA32_PPIN_CTL MSRs.
        /// </summary>
        internal static string IA32_PPIN {
            get {
                return ResourceManager.GetString("IA32_PPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_TSC_ADJUST MSR.
        /// </summary>
        internal static string IA32_TSC_ADJUST {
            get {
                return ResourceManager.GetString("IA32_TSC_ADJUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA64 processor emulating in x86 mode.
        /// </summary>
        internal static string IA64 {
            get {
                return ResourceManager.GetString("IA64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect branch prediction barrier software control available, Spectre mitigation for branch prediction side channel timing attacks.
        /// </summary>
        internal static string IBPB {
            get {
                return ResourceManager.GetString("IBPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect branch restricted speculation, Spectre mitigation enabled.
        /// </summary>
        internal static string IBRS {
            get {
                return ResourceManager.GetString("IBRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBRS always on mode.
        /// </summary>
        internal static string IBRS_ALL {
            get {
                return ResourceManager.GetString("IBRS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect branch restricted speculation (IBRS) and indirect branch predictor barrier (IBPB).
        /// </summary>
        internal static string IBRS_IBPB {
            get {
                return ResourceManager.GetString("IBRS_IBPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBRS preferred.
        /// </summary>
        internal static string IBRS_PREF {
            get {
                return ResourceManager.GetString("IBRS_PREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBRS provides Same Mode Protection.
        /// </summary>
        internal static string IBRS_SMP {
            get {
                return ResourceManager.GetString("IBRS_SMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction based sampling.
        /// </summary>
        internal static string IBS {
            get {
                return ResourceManager.GetString("IBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBINVD/WBNOINVD instructions are interruptible.
        /// </summary>
        internal static string INT_WBINVD {
            get {
                return ResourceManager.GetString("INT_WBINVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel Processor Trace.
        /// </summary>
        internal static string INTEL_PT {
            get {
                return ResourceManager.GetString("INTEL_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVLPGB and TLBSYNC instruction supported.
        /// </summary>
        internal static string INVLPGB {
            get {
                return ResourceManager.GetString("INVLPGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVLPGB support for invalidating guest nested translations.
        /// </summary>
        internal static string INVLPGB_NESTED {
            get {
                return ResourceManager.GetString("INVLPGB_NESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVPCID instruction for system software that manages process-context identifiers.
        /// </summary>
        internal static string INVPCID {
            get {
                return ResourceManager.GetString("INVPCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_SPEC_CTRL MSR allows control of IPRED_DIS control.
        /// </summary>
        internal static string IPRED_CTRL {
            get {
                return ResourceManager.GetString("IPRED_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Retired Counter MSR available.
        /// </summary>
        internal static string IRPERF {
            get {
                return ResourceManager.GetString("IRPERF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Locker.
        /// </summary>
        internal static string KL {
            get {
                return ResourceManager.GetString("KL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_FLUSH_CMD MSR supported.
        /// </summary>
        internal static string L1D_FLUSH {
            get {
                return ResourceManager.GetString("L1D_FLUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Addressing 57-bit and 5-Level Paging.
        /// </summary>
        internal static string LA57 {
            get {
                return ResourceManager.GetString("LA57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Address Masking.
        /// </summary>
        internal static string LAM {
            get {
                return ResourceManager.GetString("LAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural Last Branch Records.
        /// </summary>
        internal static string LBR {
            get {
                return ResourceManager.GetString("LBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Mode. Access to 64-bit instructions and registers, also known as x86_64 or x64.
        /// </summary>
        internal static string LM {
            get {
                return ResourceManager.GetString("LM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight profiling support.
        /// </summary>
        internal static string LWP {
            get {
                return ResourceManager.GetString("LWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Bandwidth Enforcement.
        /// </summary>
        internal static string MBE {
            get {
                return ResourceManager.GetString("MBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine-Check Architecture.
        /// </summary>
        internal static string MCA {
            get {
                return ResourceManager.GetString("MCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor does not exhibit MXCSR configuration dependent timing and no mitigation necessary.
        /// </summary>
        internal static string MCDT_NO {
            get {
                return ResourceManager.GetString("MCDT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine-Check Exception.
        /// </summary>
        internal static string MCE {
            get {
                return ResourceManager.GetString("MCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCOMMIT instruction supported.
        /// </summary>
        internal static string MCOMMIT {
            get {
                return ResourceManager.GetString("MCOMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD_CLEAR supported.
        /// </summary>
        internal static string MD_CLEAR {
            get {
                return ResourceManager.GetString("MD_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misaligned SSE mode.
        /// </summary>
        internal static string MISALIGNSSE {
            get {
                return ResourceManager.GetString("MISALIGNSSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMX Technologies, Multimedia Extensions.
        /// </summary>
        internal static string MMX {
            get {
                return ResourceManager.GetString("MMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMD extensions to MMX instructions.
        /// </summary>
        internal static string MMXEXT {
            get {
                return ResourceManager.GetString("MMXEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONITOR and MWAIT instructions.
        /// </summary>
        internal static string MONITOR {
            get {
                return ResourceManager.GetString("MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONITORX instruction support.
        /// </summary>
        internal static string MONITORX {
            get {
                return ResourceManager.GetString("MONITORX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVBE (big-endian) instruction.
        /// </summary>
        internal static string MOVBE {
            get {
                return ResourceManager.GetString("MOVBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVDIR64B instruction.
        /// </summary>
        internal static string MOVDIR64B {
            get {
                return ResourceManager.GetString("MOVDIR64B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVDIRI instruction.
        /// </summary>
        internal static string MOVDIRI {
            get {
                return ResourceManager.GetString("MOVDIRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Processor capable. AMD K7 processors prior to CPUID=0662h may report 0 even if they are MP-capable..
        /// </summary>
        internal static string MP {
            get {
                return ResourceManager.GetString("MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Memory Protection Extensions.
        /// </summary>
        internal static string MPX {
            get {
                return ResourceManager.GetString("MPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Specific Registers.
        /// </summary>
        internal static string MSR {
            get {
                return ResourceManager.GetString("MSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Type Range Registers.
        /// </summary>
        internal static string MTRR {
            get {
                return ResourceManager.GetString("MTRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node ID: MSR C001_100Ch.
        /// </summary>
        internal static string NODEID {
            get {
                return ResourceManager.GetString("NODEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS has set CR4.PKE to enable protection keys (and the RDPKRU/WRPKRU instructions).
        /// </summary>
        internal static string OSPKE {
            get {
                return ResourceManager.GetString("OSPKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS visible workaround. Indicates OS-visible workaround support for the Operating System.
        /// </summary>
        internal static string OSVW {
            get {
                return ResourceManager.GetString("OSVW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS-Enabled Extended State Management.
        /// </summary>
        internal static string OSXSAVE {
            get {
                return ResourceManager.GetString("OSXSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Address Extension.
        /// </summary>
        internal static string PAE {
            get {
                return ResourceManager.GetString("PAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Flush MSR available.
        /// </summary>
        internal static string PAGEFLUSHMSR {
            get {
                return ResourceManager.GetString("PAGEFLUSHMSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Attribute Table.
        /// </summary>
        internal static string PAT {
            get {
                return ResourceManager.GetString("PAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Break Enable.
        /// </summary>
        internal static string PBE {
            get {
                return ResourceManager.GetString("PBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Context Identifiers.
        /// </summary>
        internal static string PCID {
            get {
                return ResourceManager.GetString("PCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCLMULQDQ Instruction.
        /// </summary>
        internal static string PCLMULQDQ {
            get {
                return ResourceManager.GetString("PCLMULQDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Memory PCOMMIT instruction (deprecated, hardware manufacturers support ADR - Asynchronous DRAM refresh).
        /// </summary>
        internal static string PCOMMIT {
            get {
                return ResourceManager.GetString("PCOMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform configuration (Memory Encryption Technologies instructions).
        /// </summary>
        internal static string PCONFIG {
            get {
                return ResourceManager.GetString("PCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfmon and Debug Capability.
        /// </summary>
        internal static string PDCM {
            get {
                return ResourceManager.GetString("PDCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor performance counter extensions support. Indicates support for MSRC001_020[A,8,6,4,2,0] and MSRC001_020[B,9,7,5,3,1].
        /// </summary>
        internal static string PERFCTREXTCORE {
            get {
                return ResourceManager.GetString("PERFCTREXTCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB performance counter extensions support. Indicates support for MSRC001_024[6,4,2,0] and MSRC001_024[7,5,3,1].
        /// </summary>
        internal static string PERFCTREXTNB {
            get {
                return ResourceManager.GetString("PERFCTREXTNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2I perf counter extensions (MSRs C001_023[0...7]h) (Fam 15h/16h). L3 perf counter extensions (MSRs C001_023[0...B]h) (Fam 17h).
        /// </summary>
        internal static string PERFL2I {
            get {
                return ResourceManager.GetString("PERFL2I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance time-stamp counter.
        /// </summary>
        internal static string PERFTSC {
            get {
                return ResourceManager.GetString("PERFTSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Global Enable bit in CR4.
        /// </summary>
        internal static string PGE {
            get {
                return ResourceManager.GetString("PGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection keys for supervisor-mode pages.
        /// </summary>
        internal static string PKS {
            get {
                return ResourceManager.GetString("PKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Keys for user-mode pages.
        /// </summary>
        internal static string PKU {
            get {
                return ResourceManager.GetString("PKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPCNT, population count, instruction.
        /// </summary>
        internal static string POPCNT {
            get {
                return ResourceManager.GetString("POPCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected Processor Inventory Number. can be enabled for privileged system inventory agent to Read PPIN.
        /// </summary>
        internal static string PPIN {
            get {
                return ResourceManager.GetString("PPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefetch data into caches in anticipation of a write.
        /// </summary>
        internal static string PREFETCHW {
            get {
                return ResourceManager.GetString("PREFETCHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefetch data into caches in anticipation of a write, with T1 hint. Intel(R) Xeon Phi(TM) only.
        /// </summary>
        internal static string PREFETCHWT1 {
            get {
                return ResourceManager.GetString("PREFETCHWT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size Extension.
        /// </summary>
        internal static string PSE {
            get {
                return ResourceManager.GetString("PSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36-bit Page Size Extension.
        /// </summary>
        internal static string PSE_36 {
            get {
                return ResourceManager.GetString("PSE-36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_SPEC_CTRL MSR allows disable of Fast Store Forwarding Predictor without disabling Speculative Store Bypass.
        /// </summary>
        internal static string PSFD {
            get {
                return ResourceManager.GetString("PSFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Serial Number is present and enabled.
        /// </summary>
        internal static string PSN {
            get {
                return ResourceManager.GetString("PSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Processor ID and IA32_TSX_AUX.
        /// </summary>
        internal static string RDPID {
            get {
                return ResourceManager.GetString("RDPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDPRU instruction supported.
        /// </summary>
        internal static string RDPRU {
            get {
                return ResourceManager.GetString("RDPRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-chip random number generator, RDRAND instruction.
        /// </summary>
        internal static string RDRAND {
            get {
                return ResourceManager.GetString("RDRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDSEED (read random seed) instruction.
        /// </summary>
        internal static string RDSEED {
            get {
                return ResourceManager.GetString("RDSEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel Resource Director Technology - Allocation Capability.
        /// </summary>
        internal static string RDT_A {
            get {
                return ResourceManager.GetString("RDT-A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel Resource Director Technology - Monitoring Capability.
        /// </summary>
        internal static string RDT_M {
            get {
                return ResourceManager.GetString("RDT-M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDTSCP and IA32_TSX_AUX supported.
        /// </summary>
        internal static string RDTSCP {
            get {
                return ResourceManager.GetString("RDTSCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_SPEC_CTRL MSR allows disable of RRSBA behaviour.
        /// </summary>
        internal static string RRSBA_CTRL {
            get {
                return ResourceManager.GetString("RRSBA_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSX restricted transactional memory.
        /// </summary>
        internal static string RTM {
            get {
                return ResourceManager.GetString("RTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, any execution of XBEGIN immediately aborts and transitions to the
        ///specified fallback address..
        /// </summary>
        internal static string RTM_ALWAYS_ABORT {
            get {
                return ResourceManager.GetString("RTM_ALWAYS_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silicon Debug (IA32_DEBUG_INTERFACE MSR).
        /// </summary>
        internal static string SDBG {
            get {
                return ResourceManager.GetString("SDBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast System Call, SYSENTER and SYSEXIT instructions.
        /// </summary>
        internal static string SEP {
            get {
                return ResourceManager.GetString("SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialize instruction execution.
        /// </summary>
        internal static string SERIALIZE {
            get {
                return ResourceManager.GetString("SERIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Encrypted Virtualization supported.
        /// </summary>
        internal static string SEV {
            get {
                return ResourceManager.GetString("SEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Software Guard Extensions.
        /// </summary>
        internal static string SGX {
            get {
                return ResourceManager.GetString("SGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attestation Services for Intel SGX is supported.
        /// </summary>
        internal static string SGX_KEYS {
            get {
                return ResourceManager.GetString("SGX-KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGX Launch Configuration.
        /// </summary>
        internal static string SGX_LC {
            get {
                return ResourceManager.GetString("SGX_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel(R) Secure Hash Algorithm Extensions.
        /// </summary>
        internal static string SHA {
            get {
                return ResourceManager.GetString("SHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKINIT and STGI are supported, independent of the value of MSRC000_0080[SVME].
        /// </summary>
        internal static string SKINIT {
            get {
                return ResourceManager.GetString("SKINIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Mode Access Prevention.
        /// </summary>
        internal static string SMAP {
            get {
                return ResourceManager.GetString("SMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Memory Encryption supported.
        /// </summary>
        internal static string SME {
            get {
                return ResourceManager.GetString("SME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Mode Execution Prevention.
        /// </summary>
        internal static string SMEP {
            get {
                return ResourceManager.GetString("SMEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safer Mode Extensions.
        /// </summary>
        internal static string SMX {
            get {
                return ResourceManager.GetString("SMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEV (Secure Encrypted Virtualization) Secure Nested Paging supported.
        /// </summary>
        internal static string SNP {
            get {
                return ResourceManager.GetString("SNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates support for the IA32_MCU_OPT_CTRL MSR and indicates its bit 0
        ///(RNGDS_MITG_DIS) is also supported.
        /// </summary>
        internal static string SRBDS_CTRL {
            get {
                return ResourceManager.GetString("SRBDS_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Cache implements Self Snoop.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speculative Store Bypass Disable (SSBD).
        /// </summary>
        internal static string SSBD {
            get {
                return ResourceManager.GetString("SSBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions.
        /// </summary>
        internal static string SSE {
            get {
                return ResourceManager.GetString("SSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 2.
        /// </summary>
        internal static string SSE2 {
            get {
                return ResourceManager.GetString("SSE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 3.
        /// </summary>
        internal static string SSE3 {
            get {
                return ResourceManager.GetString("SSE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 4.1.
        /// </summary>
        internal static string SSE4_1 {
            get {
                return ResourceManager.GetString("SSE4.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming SIMD Extensions 4.2.
        /// </summary>
        internal static string SSE4_2 {
            get {
                return ResourceManager.GetString("SSE4.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTRQ, INSERTQ, MOVNTSS, and MOVNTSD instruction support.
        /// </summary>
        internal static string SSE4A {
            get {
                return ResourceManager.GetString("SSE4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Streaming SIMD Extensions 3.
        /// </summary>
        internal static string SSSE3 {
            get {
                return ResourceManager.GetString("SSSE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single thread indirect branch predictors (STIBP).
        /// </summary>
        internal static string STIBP {
            get {
                return ResourceManager.GetString("STIBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STIBP always on mode.
        /// </summary>
        internal static string STIBP_ALL {
            get {
                return ResourceManager.GetString("STIBP_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming performance monitor architecture. Indicates support for
        ///MSRC001_028[C:8,4:1]. Reserved from #24594, rev 3.21, May 2013.
        /// </summary>
        internal static string STREAMPERFMON {
            get {
                return ResourceManager.GetString("STREAMPERFMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Virtual Machine.
        /// </summary>
        internal static string SVM {
            get {
                return ResourceManager.GetString("SVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSCALL and SYSRET instructions are supported.
        /// </summary>
        internal static string SYSCALL {
            get {
                return ResourceManager.GetString("SYSCALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing bit manipulation instruction support.
        /// </summary>
        internal static string TBM {
            get {
                return ResourceManager.GetString("TBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation cache extension, EFER.TCE.
        /// </summary>
        internal static string TCE {
            get {
                return ResourceManager.GetString("TCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Monitor.
        /// </summary>
        internal static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Monitor 2.
        /// </summary>
        internal static string TM2 {
            get {
                return ResourceManager.GetString("TM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA32_TME MSR capabilities are supported.
        /// </summary>
        internal static string TME_EN {
            get {
                return ResourceManager.GetString("TME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topology extensions support.
        /// </summary>
        internal static string TOPX {
            get {
                return ResourceManager.GetString("TOPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp Counter.
        /// </summary>
        internal static string TSC {
            get {
                return ResourceManager.GetString("TSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp Counter Deadline supported by APIC.
        /// </summary>
        internal static string TSC_DEADLINE {
            get {
                return ResourceManager.GetString("TSC-DEADLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTM_FORCE_ABORT supported. Processors that set this bit support the
        ///IA32_TSX_FORCE_ABORT MSR. They allow software to set IA32_TSX_FORCE_ABORT[0]
        ///(RTM_FORCE_ABORT).
        /// </summary>
        internal static string TSX_FORCE_ABORT {
            get {
                return ResourceManager.GetString("TSX_FORCE_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSX suspend load address tracking.
        /// </summary>
        internal static string TSXLDTRK {
            get {
                return ResourceManager.GetString("TSXLDTRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Space Interrupts.
        /// </summary>
        internal static string UINTR {
            get {
                return ResourceManager.GetString("UINTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-mode Instruction Prevention.
        /// </summary>
        internal static string UMIP {
            get {
                return ResourceManager.GetString("UMIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectored AES 128-bit on vectored data 256bit registers.
        /// </summary>
        internal static string VAES {
            get {
                return ResourceManager.GetString("VAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual 8086 Mode Extensions.
        /// </summary>
        internal static string VME {
            get {
                return ResourceManager.GetString("VME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Permission Levels supported.
        /// </summary>
        internal static string VMPL {
            get {
                return ResourceManager.GetString("VMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine Extensions.
        /// </summary>
        internal static string VMX {
            get {
                return ResourceManager.GetString("VMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectored VPCLMULQDQ Instruction.
        /// </summary>
        internal static string VPCLMULQDQ {
            get {
                return ResourceManager.GetString("VPCLMULQDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Transparent Encryption for SEV. The Virtual Transparent Encryption feature can be enabled to force all memory accesses within an SEV guest to be encrypted with the guest&apos;s key.
        /// </summary>
        internal static string VTE {
            get {
                return ResourceManager.GetString("VTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User level monitor/wait (TPAUSE, UMONITOR, UMWAIT) instructions.
        /// </summary>
        internal static string WAITPKG {
            get {
                return ResourceManager.GetString("WAITPKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBNOINVD instruction supported.
        /// </summary>
        internal static string WBNOINVD {
            get {
                return ResourceManager.GetString("WBNOINVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog timer support. See APM2 and APM3. Indicates support for
        ///MSRC001_0074.
        /// </summary>
        internal static string WDT {
            get {
                return ResourceManager.GetString("WDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended APIC support.
        /// </summary>
        internal static string X2APIC {
            get {
                return ResourceManager.GetString("X2APIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Disable bit.
        /// </summary>
        internal static string XD {
            get {
                return ResourceManager.GetString("XD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XGETBV with ECX = 1 supported.
        /// </summary>
        internal static string XGETBV {
            get {
                return ResourceManager.GetString("XGETBV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended operation support.
        /// </summary>
        internal static string XOP {
            get {
                return ResourceManager.GetString("XOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSAVE/XSTOR states.
        /// </summary>
        internal static string XSAVE {
            get {
                return ResourceManager.GetString("XSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSAVEC and compact XRSTOR supported.
        /// </summary>
        internal static string XSAVEC {
            get {
                return ResourceManager.GetString("XSAVEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSAVEOPT is available.
        /// </summary>
        internal static string XSAVEOPT {
            get {
                return ResourceManager.GetString("XSAVEOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSAVES, XRSTOR, and XSS are supported.
        /// </summary>
        internal static string XSAVES {
            get {
                return ResourceManager.GetString("XSAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xTPR Update Control, disable sending task priority messages.
        /// </summary>
        internal static string XTPR {
            get {
                return ResourceManager.GetString("XTPR", resourceCulture);
            }
        }
    }
}
