//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.Diagnostics.CpuIdWin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.Diagnostics.CpuIdWin.Resources.UserInterface", typeof(UserInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Memory Features.
        /// </summary>
        internal static string fgEncryptedMemory {
            get {
                return ResourceManager.GetString("fgEncryptedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Features.
        /// </summary>
        internal static string fgExtendedFeatures {
            get {
                return ResourceManager.GetString("fgExtendedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Feature Identifiers.
        /// </summary>
        internal static string fgExtendedFeaturesIdentifiers {
            get {
                return ResourceManager.GetString("fgExtendedFeaturesIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended State.
        /// </summary>
        internal static string fgExtendedState {
            get {
                return ResourceManager.GetString("fgExtendedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight Profiling Features.
        /// </summary>
        internal static string fgLightWeightProfiling {
            get {
                return ResourceManager.GetString("fgLightWeightProfiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Optimization Features.
        /// </summary>
        internal static string fgPerformanceOptimizations {
            get {
                return ResourceManager.GetString("fgPerformanceOptimizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Sampling Features.
        /// </summary>
        internal static string fgPerformanceSampling {
            get {
                return ResourceManager.GetString("fgPerformanceSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Features.
        /// </summary>
        internal static string fgStandardFeatures {
            get {
                return ResourceManager.GetString("fgStandardFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Extended Features.
        /// </summary>
        internal static string fgStructuredExtendedFeatures {
            get {
                return ResourceManager.GetString("fgStructuredExtendedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Memory Features.
        /// </summary>
        internal static string fgSvmFeatures {
            get {
                return ResourceManager.GetString("fgSvmFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Feature Group.
        /// </summary>
        internal static string fgUnknown {
            get {
                return ResourceManager.GetString("fgUnknown", resourceCulture);
            }
        }
    }
}
